# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import messenger_pb2 as protos_dot_messenger__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in protos/messenger_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LearningMessengerStub(object):
    """The Learning Messenger Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLearningStatus = channel.unary_unary(
                '/messenger.LearningMessenger/GetLearningStatus',
                request_serializer=protos_dot_messenger__pb2.StatusRequest.SerializeToString,
                response_deserializer=protos_dot_messenger__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.StreamLearnings = channel.unary_stream(
                '/messenger.LearningMessenger/StreamLearnings',
                request_serializer=protos_dot_messenger__pb2.TopicRequest.SerializeToString,
                response_deserializer=protos_dot_messenger__pb2.LearningUpdate.FromString,
                _registered_method=True)
        self.SubmitResearchNotes = channel.stream_unary(
                '/messenger.LearningMessenger/SubmitResearchNotes',
                request_serializer=protos_dot_messenger__pb2.ResearchNote.SerializeToString,
                response_deserializer=protos_dot_messenger__pb2.SummaryResponse.FromString,
                _registered_method=True)
        self.CollaborativeFeed = channel.stream_stream(
                '/messenger.LearningMessenger/CollaborativeFeed',
                request_serializer=protos_dot_messenger__pb2.FeedUpdate.SerializeToString,
                response_deserializer=protos_dot_messenger__pb2.FeedUpdate.FromString,
                _registered_method=True)


class LearningMessengerServicer(object):
    """The Learning Messenger Service
    """

    def GetLearningStatus(self, request, context):
        """Unary: A basic Request-Response call
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamLearnings(self, request, context):
        """Server Streaming: Server pushes multiple updates to the client
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitResearchNotes(self, request_iterator, context):
        """Client Streaming: Client sends a stream of research notes to the server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CollaborativeFeed(self, request_iterator, context):
        """Bi-directional Streaming: Real-time collaborative chat/updates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LearningMessengerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLearningStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLearningStatus,
                    request_deserializer=protos_dot_messenger__pb2.StatusRequest.FromString,
                    response_serializer=protos_dot_messenger__pb2.StatusResponse.SerializeToString,
            ),
            'StreamLearnings': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamLearnings,
                    request_deserializer=protos_dot_messenger__pb2.TopicRequest.FromString,
                    response_serializer=protos_dot_messenger__pb2.LearningUpdate.SerializeToString,
            ),
            'SubmitResearchNotes': grpc.stream_unary_rpc_method_handler(
                    servicer.SubmitResearchNotes,
                    request_deserializer=protos_dot_messenger__pb2.ResearchNote.FromString,
                    response_serializer=protos_dot_messenger__pb2.SummaryResponse.SerializeToString,
            ),
            'CollaborativeFeed': grpc.stream_stream_rpc_method_handler(
                    servicer.CollaborativeFeed,
                    request_deserializer=protos_dot_messenger__pb2.FeedUpdate.FromString,
                    response_serializer=protos_dot_messenger__pb2.FeedUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'messenger.LearningMessenger', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('messenger.LearningMessenger', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LearningMessenger(object):
    """The Learning Messenger Service
    """

    @staticmethod
    def GetLearningStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messenger.LearningMessenger/GetLearningStatus',
            protos_dot_messenger__pb2.StatusRequest.SerializeToString,
            protos_dot_messenger__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamLearnings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/messenger.LearningMessenger/StreamLearnings',
            protos_dot_messenger__pb2.TopicRequest.SerializeToString,
            protos_dot_messenger__pb2.LearningUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitResearchNotes(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/messenger.LearningMessenger/SubmitResearchNotes',
            protos_dot_messenger__pb2.ResearchNote.SerializeToString,
            protos_dot_messenger__pb2.SummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CollaborativeFeed(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/messenger.LearningMessenger/CollaborativeFeed',
            protos_dot_messenger__pb2.FeedUpdate.SerializeToString,
            protos_dot_messenger__pb2.FeedUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
