# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/messenger.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protos/messenger.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16protos/messenger.proto\x12\tmessenger\" \n\rStatusRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"1\n\x0eStatusResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tive\x18\x02 \x01(\x08\"\x1d\n\x0cTopicRequest\x12\r\n\x05topic\x18\x01 \x01(\t\"F\n\x0eLearningUpdate\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x10\n\x08progress\x18\x02 \x01(\x05\x12\x11\n\ttimestamp\x18\x03 \x01(\t\"\x1c\n\x0cResearchNote\x12\x0c\n\x04text\x18\x01 \x01(\t\"7\n\x0fSummaryResponse\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\x12\x15\n\rfinal_summary\x18\x02 \x01(\t\"+\n\nFeedUpdate\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2\xbb\x02\n\x11LearningMessenger\x12H\n\x11GetLearningStatus\x12\x18.messenger.StatusRequest\x1a\x19.messenger.StatusResponse\x12G\n\x0fStreamLearnings\x12\x17.messenger.TopicRequest\x1a\x19.messenger.LearningUpdate0\x01\x12L\n\x13SubmitResearchNotes\x12\x17.messenger.ResearchNote\x1a\x1a.messenger.SummaryResponse(\x01\x12\x45\n\x11\x43ollaborativeFeed\x12\x15.messenger.FeedUpdate\x1a\x15.messenger.FeedUpdate(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.messenger_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUSREQUEST']._serialized_start=37
  _globals['_STATUSREQUEST']._serialized_end=69
  _globals['_STATUSRESPONSE']._serialized_start=71
  _globals['_STATUSRESPONSE']._serialized_end=120
  _globals['_TOPICREQUEST']._serialized_start=122
  _globals['_TOPICREQUEST']._serialized_end=151
  _globals['_LEARNINGUPDATE']._serialized_start=153
  _globals['_LEARNINGUPDATE']._serialized_end=223
  _globals['_RESEARCHNOTE']._serialized_start=225
  _globals['_RESEARCHNOTE']._serialized_end=253
  _globals['_SUMMARYRESPONSE']._serialized_start=255
  _globals['_SUMMARYRESPONSE']._serialized_end=310
  _globals['_FEEDUPDATE']._serialized_start=312
  _globals['_FEEDUPDATE']._serialized_end=355
  _globals['_LEARNINGMESSENGER']._serialized_start=358
  _globals['_LEARNINGMESSENGER']._serialized_end=673
# @@protoc_insertion_point(module_scope)
